export const INDIA_WORDS = [
  "Pani Puri",
  "Vada Pav",
  "Samosas",
  "Dosa",
  "Idli",
  "Chole Bhature",
  "Pav Bhaji",
  "Biryani",
  "Butter Chicken",
  "Dal Makhani",
  "Rajma Chawal",
  "Poha",
  "Litti Chokha",
  "Malabar Parotta",
  "Bisi Bele Bath",
  "Lemon Rice",
  "Curd Rice",
  "Rasam",
  "Momos",
  "Thukpa",
  "Kathi Rolls",
  "Aloo Paratha",
  "Tandoori Food",
  "Kebabs",
  "Maggi Noodles",
  "Chai",
  "Filter Coffee",
  "Lassi",
  "Nimbu Pani",
  "Sugarcane Juice",
  "Jaljeera",
  "Aam Panna",
  "Thandai",
  "Kulfi",
  "Jalebi",
  "Gulab Jamun",
  "Rasgulla",
  "Mysore Pak",
  "Kaju Katli",
  "Motichoor Laddoos",
  "Modak",
  "Gajar Ka Halwa",
  "Shrikhand",
  "Falooda",
  "Papad",
  "Sev Puri",
  "Dahi Puri",
  "Paapdi Chaat",
  "Parle-G Biscuits",
  "The Taj Mahal",
  "India Gate",
  "The Red Fort",
  "Qutub Minar",
  "Local Trains",
  "Diwali",
  "Holi",
  "Navratri Garba",
  "Durga Puja Pandals",
  "Ganesh Chaturthi",
  "Onam Sadya",
  "Pongal",
  "Eid Feasts",
  "Raksha Bandhan",
  "Janmashtami",
  "Independence Day Celebrations",
  "Rangoli",
  "Henna Art",
  "Sarees",
  "Kurtas",
  "Jhumkas",
  "Bollywood Dance Numbers",
  "Shah Rukh Khan",
  "Shahid Kapoor",
  "Dhurandhar",
  "Ranbir Kapoor",
  "Abhishek Bachchan",
  "Hrithik Roshan",
  "Amitabh Bachchan",
  "Rajinikanth",
  "Sangeet Functions",
  "Indian Weddings",
  "A. R. Rahman Soundtracks",
  "Arijit Singh Songs",
  "Lata Mangeshkar Classics",
  "Punjabi Songs",
  "Desi Hip-Hop",
  "Carnatic Music",
  "Tabla Solos",
  "Sitar Music",
  "Antakshari",
  "Kaun Banega Crorepati",
  "CID",
  "Taarak Mehta Ka Ooltah Chashmah",
  "Saas-Bahu Serials",
  "Amar Chitra Katha",
  "Tinkle Comics",
  "Cricket",
  "IPL",
  "India-Pakistan Matches",
  "Sachin Tendulkar",
  "M. S. Dhoni",
  "Virat Kohli",
  "Kabaddi",
  "Kho-Kho",
  "Carrom",
  "Lagori",
  "Ludo",
  "Auto-Rickshaw Rides",
  "Roadside Dhabas",
  "Old Monk Rum",
  "Thums Up",
  "Frooti",
  "Paper Boat Drinks",
  "Swiggy/Zomato",
  "Zepto/BlinkIt",
  "Priyanka Chopra Jonas",
  "Lungi Attire",
  "Thaali Meals",
  "Narendra Modi",
  "Aamras",
  "Classical Dance",
  "Medu Vada",
  "Rava Dosa",
  "Neer Dosa",
  "Akki Roti",
  "Dabeli",
  "Frankie Rolls",
  "Kachori",
  "Pakodas",
  "Roomali Roti",
  "Paneer Tikka",
  "Malai Kofta",
  "Khichdi",
  "Baingan Bharta",
  "Chicken 65",
  "Fish Fry",
  "Prawn Curry",
  "Egg Curry",
  "Bun Maska",
  "Ghee Roast",
  "Kokum Sherbet",
  "Badam Milk",
  "Rabdi",
  "Soan Papdi",
  "Ras Malai",
  "Salman Khan",
  "Aamir Khan",
  "Akshay Kumar",
  "Sanjay Dutt",
  "Irrfan Khan",
  "Nawazuddin Siddiqui",
  "Deepika Padukone",
  "Alia Bhatt",
  "Katrina Kaif",
  "Zindagi Na Milegi Dobara",
  "Kabhi Khushi Kabhie Gham",
  "Munna Bhai M.B.B.S.",
  "Taare Zameen Par",
  "3 Idiots",
  "RRR",
  "Sunil Chhetri",
  "Puri",
  "Kurkure",
  "Lays Blue",
  "Dairy Milk Silk",
  "Hide & Seek Biscuits",
  "Good Day Biscuits",
  "Marie Biscuits",
  "Bourbon Biscuits",
  "Appy Fizz",
  "Kala Khatta Gola",
  "Coconut Water",
  "Goli Soda",
  "Bucket Baths",
  "Incense Sticks",
  "School Bus Rides",
  "Aloo Bhujia",
  "Little Hearts Biscuits",
  "Jim Jam",
  "Rusk",
  "Boomer Chewing Gum",
  "Phantom Sweet Cigarettes",
  "Bytes Chocolate",
  "Hippo Chips (RIP)",
  "Fryums",
  "Scooter Rides"
] as const;
