export const NSFW_WORDS = [
  "Making Out",
  "French Kissing",
  "Neck Kisses",
  "Ear Nibbling",
  "Hickeys",
  "Naked Cuddling",
  "Going Commando",
  "Skinny-Dipping",
  "Sexting",
  "Grape-Fruiting",
  "Pornography",
  "Dirty Talk",
  "Pillow Talk",
  "Foreplay",
  "Morning Sex",
  "Makeup Sex",
  "One-Night Stands",
  "Friends with Benefits",
  "Age-Gap Relationships",
  "Polyamory",
  "Threesomes",
  "Orgies",
  "Nude Beaches",
  "Strip Clubs",
  "Shower Sex",
  "Car Sex",
  "The Mile-High Club",
  "BDSM",
  "Consensual Choking",
  "Lap Dances",
  "Hentai",
  "Sex Toys",
  "Flavoured Lube",
  "Handjobs",
  "Fingering",
  "Giving Oral",
  "Receiving Oral",
  "69",
  "Anal",
  "Doggystyle",
  "Pegging",
  "Facesitting",
  "Feet",
  "OnlyFans",
  "Missionary",
  "Cowgirl",
  "Reverse Cowgirl",
  "Spooning",
  "Weed",
  "Edibles",
  "Bongs",
  "Vaping",
  "Magic Mushrooms",
  "Acid",
  "Tequila",
  "Vodka",
  "Whiskey",
  "Rum",
  "Gin",
  "Long Island Iced Tea",
  "Beer Pong",
  "Furries",
  "Drinking Games",
  "Body Shots",
  "Boobs",
  "Jello Shots",
  "Cigarettes",
  "Blackjack",
  "Drunk Texting",
  "Shoplifting",
  "Tax Evasion",
  "Torrenting",
  "The Dark Web",
  "Conspiracy Theories",
  "Profanity",
  "Dark Humour",
  "Sugar Daddies",
  "Flagellation",
  "Vibrators",
  "Wet Dreams",
  "Smut",
  "Bottomless Mimosas",
] as const;
