export const POP_CULTURE_WORDS = [
  "Taylor Swift",
  "Beyoncé",
  "Michael Jackson",
  "The Beatles",
  "Rihanna",
  "Drake",
  "Kanye West",
  "Ariana Grande",
  "Justin Bieber",
  "Britney Spears",
  "Ed Sheeran",
  "Bruno Mars",
  "The Weeknd",
  "Billie Eilish",
  "Dua Lipa",
  "Shakira",
  "Eminem",
  "Snoop Dogg",
  "Kendrick Lamar",
  "Charlie Kirk",
  "Post Malone",
  "Bad Bunny",
  "Sabrina Carpenter",
  "Olivia Rodrigo",
  "Chappell Roan",
  "Lana Del Rey",
  "Harry Styles",
  "Dolly Parton",
  "ABBA",
  "Coldplay",
  "BTS",
  "One Direction",
  "Nirvana",
  "Metallica",
  "JRR Tolkien",
  "Linkin Park",
  "Queen",
  "AC/DC",
  "Green Day",
  "5 Seconds of Summer",
  "Imagine Dragons",
  "Christopher Nolan",
  "Martin Scorsese",
  "P Diddy",
  "Tom Cruise",
  "Leonardo DiCaprio",
  "Johnny Depp",
  "Robert Downey Jr.",
  "Dwayne Johnson",
  "Will Smith",
  "Tom Hanks",
  "Tom Holland",
  "Zendaya",
  "Jesus Christ",
  "Keanu Reeves",
  "Morgan Freeman",
  "Samuel L. Jackson",
  "Sydney Sweeney",
  "Jackie Chan",
  "Jennifer Aniston",
  "Anne Hathaway",
  "Scarlett Johansson",
  "Natalie Portman",
  "Margot Robbie",
  "Emma Stone",
  "Emma Watson",
  "Jennifer Lawrence",
  "Ryan Reynolds",
  "Ryan Gosling",
  "Chris Hemsworth",
  "Chris Evans",
  "Pedro Pascal",
  "Baby Yoda",
  "Timothée Chalamet",
  "Hugh Jackman",
  "Jim Carrey",
  "Steve Carell",
  "Robin Williams",
  "Bugs Bunny",
  "SpongeBob SquarePants",
  "Shrek",
  "Harry Potter",
  "Voldemort",
  "Darth Vader",
  "Luke Skywalker",
  "Iron Man",
  "Spider-Man",
  "Batman",
  "Superman",
  "The Joker",
  "Captain America",
  "Thor",
  "The Hulk",
  "Deadpool",
  "Thanos",
  "Doctor Strange",
  "Elsa",
  "Cinderella",
  "Snow White",
  "Rapunzel",
  "Aladdin",
  "Kung Fu Panda",
  "The Minions",
  "Waluigi",
  "Donkey Kong",
  "Pokemon",
  "Dragon Ball Z",
  "Naruto",
  "One Piece",
  "Scooby-Doo",
  "Tom and Jerry",
  "Mr. Bean",
  "James Bond",
  "Indiana Jones",
  "Barbie",
  "Frodo Baggins",
  "Gollum",
  "Sherlock Holmes",
  "F.R.I.E.N.D.S",
  "Sheldon Cooper",
  "Michael Scott",
  "Breaking Bad",
  "Game of Thrones",
  "Rick & Morty",
  "Donald Trump",
  "Barack Obama",
  "Vladimir Putin",
  "Queen Elizabeth II",
  "Princess Diana",
  "Mahatma Gandhi",
  "Albert Einstein",
  "Elon Musk",
  "Steve Jobs",
  "Bill Gates",
  "Mark Zuckerberg",
  "Sam Altman",
  "Jeff Bezos",
  "MrBeast",
  "Gordon Ramsay",
  "Kim Kardashian",
  "Cristiano Ronaldo",
  "Lionel Messi",
  "The Dalai Lama",
  "Osama Bin Laden",
  "Jeffrey Epstein",
  "Andrew Tate",
  "O.J. Simpson",
  "Joe Biden",
  "Star Wars",
  "Star Trek",
  "The Marvel Cinematic Universe",
  "DC Comics",
  "The Lord of the Rings",
  "Doctor Who",
  "Disney Animated Movies",
  "Lion King",
  "The Big Bang Theory",
  "The Office",
  "South Park",
  "Family Guy",
  "Modern Family",
  "How I Met Your Mother",
  "Brooklyn Nine-Nine",
  "Squid Game",
  "Bridgerton",
  "The Sopranos",
  "Black Mirror",
  "Twilight",
  "Avatar: the Last Airbender",
  "Toy Story",
  "Finding Nemo",
  "Cars",
  "The Incredibles",
  "Monsters, Inc.",
  "The Avengers",
  "Guardians of the Galaxy",
  "The TARDIS",
  "Lightsabers",
  "The Batmobile",
  "The DeLorean",
  "Krabby Patties",
  "The Omnitrix",
  "FIFA",
  "Mario Kart",
  "GTA",
  "Fortnite",
  "Minecraft",
  "Call of Duty",
  "Valorant",
  "League of Legends",
  "Among Us",
  "Super Mario Bros.",
  "Fromsoft Games",
  "Assassin's Creed",
  "Sweet Caroline",
  "Erling Haaland",
  "Kylian Mbappe",
  "The Oscars",
  "Coachella",
  "Lollapalooza",
  "Kim Jong Un",
  "Julius Caesar",
  "Abraham Lincoln",
  "George Washington",
  "Vincent Van Gogh",
  "Mozart",
  "Beethoven",
  "Adolf Hitler",
  "Joseph Stalin",
  "Genghis Khan",
  "Saddam Hussein",
  "Pablo Escobar",
  "Usain Bolt",
  "Michael Jordan",
  "LeBron James",
  "Roger Federer",
  "David Beckham",
  "Lewis Hamilton",
  "Max Verstappen",
  "David Attenborough",
  "Malala Yousafzai",
  "Greta Thunberg",
  "Pope Francis",
  "Volodymyr Zelenskyy",
  "Netanyahu",
  "Beyblades"
] as const;
